fixes Netlify CMS issue and #99 (#103)
* enhancement - adding alternate name to opensource

* bugfix for nelifycms - Update config.yml

fixes this Error loading the CMS configuration
Config Errors:
YAMLSemanticError: Indicator : missing in flow map entry at line 135, column 74: …e: 'outputs', widget: 'object', field:{name: 'home', label: 'home' , widget: l…